### ISSUE TITLE
Custom msg generation tutorial

### ISSUE THREAD

**Issue by Steplerchik** [gazebosim/gz-msgs#371]
Dear developers,

Is there any tutorial on how to create a custom gazebo msg for Gazebo Garden? Thanks in advance!

**Comment by mjcarroll** [comment]
The mechanisms for generating custom messages in Garden weren't particularly convenient.  For the most part, we added messages to the `gz-msgs9` release (or you could use them from a fork).

The closest example of using custom messages would be the networking messages generated in `gz-sim`: https://github.com/gazebosim/gz-sim/tree/gz-sim7/src/msgs

For `harmonic` forward, I would suggest checking out the tutorial and examples for the newly-exposed message generation framework: https://github.com/gazebosim/gz-msgs/pull/386
