### ISSUE TITLE
Add support for ackermann_msgs AckermannDrive and AckermannDriveStamped

### ISSUE THREAD

**Issue by retinfai** [gazebosim/gz-msgs#433]
## Desired behavior

Add support for the [AckermannDrive](http://docs.ros.org/en/jade/api/ackermann_msgs/html/msg/AckermannDrive.html) and [AckermannDriveStamped](http://docs.ros.org/en/jade/api/ackermann_msgs/html/msg/AckermannDriveStamped.html) messages

## Additional context
I am keen to add it in. 

I am writing an AckermannSteering plugin based on the gz-sim version. To accept this message

**Comment by ahcorde** [comment]
Hi @retinfai, 

feel free to open a PR, happy to review it.

**Comment by azeey** [comment]
cc @bperseghetti

**Comment by retinfai** [comment]
Closing issue, as discussed in downstream PR
